""""""""""""""""
" My Vim profile
""""""""""""""""

""""""""""""""""
" Colours 
""""""""""""""""

" Enable syntax highlighting
syntax enable

" Colour scheme
colorscheme koehler

set background=dark

set tabstop=4
